---

- name: squid | install packages
  tags:
    - package
  package:
    name: squid
  notify: restart squid

- name: squid | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/squid/{{ item }}"
  loop:
    - squid.conf
  notify:
    - restart squid

- name: squid | firewall config dir
  tags:
    - systemd
    - dir 
  file:
    path: "{{ squid_iptables_conf | dirname }}"
    state: directory

- name: squid | firewall config
  tags:
    - systemd
    - config
  template:
    src: "iptables.conf.j2"
    dest: "{{ squid_iptables_conf }}"
  notify:
    - daemon-reload
    - restart squid

- name: squid | service
  tags:
    - service
  service:
    name: squid
    state: started
    enabled: yes
