---

- name: socks-proxy | systemd service
  tags:
    - systemd
    - config
  template:
    src: "{{ item.src }}.j2"
    dest: "/etc/systemd/system/socks-proxy.{{ item.dest | d }}{{ item.src }}"
  loop:
    - { src: service }
    - { src: iptables.conf, dest: service.d/ }
  notify:
    - daemon-reload
    - restart socks-proxy

- name: socks-proxy | service
  tags:
    - service
  service:
    name: socks-proxy
    state: started
    enabled: yes
